# Generated by Django 4.1.7 on 2023-03-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportsSystem', '0002_alter_consultor_id_alter_proyecto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultor',
            name='status',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='MLastName',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='PlastName',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='mail',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(max_length=4),
        ),
    ]
