# Generated by Django 4.1.7 on 2023-03-17 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportsSystem', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='consultor',
        ),
        migrations.DeleteModel(
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='reportes',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
